### ISSUE TITLE
degenerated bases & scrappie squiggle

### ISSUE THREAD

**Issue by splaisan** [Psy-Fer/SquiggleKit#21]
IUPAC bases are apparently not supported by scrappie to create the kmers
I cross-reference my scrappie request **[here](https://github.com/nanoporetech/scrappie/issues/36)** in case someone has a solution

thanks

**Comment by Psy-Fer** [comment]
I've commented on the linked issue.
There may be other ways to go about what you want, depending on what your goal is.

**Comment by Psy-Fer** [comment]
You can pm me on twitter if you wish to talk privately about that.
@Psy_Fer_

**Comment by Psy-Fer** [comment]
Happy to continue to chat here if your like.

**Comment by splaisan** [comment]
sure, let me try some now that I finally could build scrappie from source (failed miserably using conda and pip)
I will get some test fast5 data and see if I can spot the two 16S primers with MotifSeq.py.
I will post here when I have issues or results whichever comes first :-)

**Comment by Psy-Fer** [comment]
Was there an issue with my instructions for getting scrappie on python3 working with pip?

**Comment by splaisan** [comment]
with conda it was spitting a page of package incompatibilities but I read that the conda build is not maintained by the makers of the tool. With pip it apparently installed but the command was not available for use in the conda env ??
It could have been my server which has been so much tweaked that it sometimes makes strange things. 
I then took the source from the ONT git and installed it on the server with success (I could create a kmer from a primer and discover the issue with undefined bases).
I am not incriminating your instruction, more think it was my server.
If you want to see the errors with conda I can probably reproduce them in a fresh env.

**Comment by splaisan** [comment]
Hi James,

I thought I had solved the install issues but not.
When I run MotifFind -h as:

```
(base) $ /opt/biotools/miniconda3/bin/python /opt/biotools/SquiggleKit/MotifSeq.py -h
Traceback (most recent call last):
  File "/opt/biotools/SquiggleKit/MotifSeq.py", line 12, in <module>
    from mlpy import dtw_subsequence
ModuleNotFoundError: No module named 'mlpy'
```

?? mlpy is installed system-wide but not seen in this conda env and I need to work in conda to preserve my system env, so I try to install mlpy locally too

```
(base) $ conda install mlpy
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                                           
                                                                                                                                                                                                 
UnsatisfiableError: The following specifications were found                                                                                                                                      
to be incompatible with the existing python installation in your environment:

Specifications:

  - mlpy -> python[version='>=3.6,<3.7.0a0']

Your python: python=3.7

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with each other:



Package wheel conflicts for:
python=3.7 -> pip -> wheel
mlpy -> python[version='>=3.6,<3.7.0a0'] -> pip -> wheel
Package certifi conflicts for:
python=3.7 -> pip -> setuptools -> certifi[version='>=2016.09']
mlpy -> python[version='>=3.6,<3.7.0a0'] -> pip -> setuptools -> certifi[version='>=2016.09']
Package setuptools conflicts for:
mlpy -> python[version='>=3.6,<3.7.0a0'] -> pip -> setuptools
python=3.7 -> pip -> setuptools
Package pip conflicts for:
python=3.7 -> pip
mlpy -> python[version='>=3.6,<3.7.0a0'] -> pip
Package ca-certificates conflicts for:
python=3.7 -> openssl[version='>=1.1.1b,<1.1.2a'] -> ca-certificates
mlpy -> python[version='>=3.6,<3.7.0a0'] -> openssl=1.0 -> ca-certificates
```

my conda info and list

```
(base) $ conda info

     active environment : base
    active env location : /opt/biotools/miniconda3
            shell level : 1
       user config file : /home/luna.kuleuven.be/u0002316/.condarc
 populated config files : /home/luna.kuleuven.be/u0002316/.condarc
          conda version : 4.7.12
    conda-build version : not installed
         python version : 3.7.4.final.0
       virtual packages : 
       base environment : /opt/biotools/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
                          https://conda.anaconda.org/sagrudd/linux-64
                          https://conda.anaconda.org/sagrudd/noarch
          package cache : /opt/biotools/miniconda3/pkgs
                          /home/luna.kuleuven.be/u0002316/.conda/pkgs
       envs directories : /opt/biotools/miniconda3/envs
                          /home/luna.kuleuven.be/u0002316/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.4 Linux/4.4.0-164-generic ubuntu/16.04.6 glibc/2.23
                UID:GID : 664444851:664200513
             netrc file : None
           offline mode : False

(base) $ conda list
# packages in environment at /opt/biotools/miniconda3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
asn1crypto                0.24.0                   py37_0  
ca-certificates           2019.5.15                     1  
certifi                   2019.6.16                py37_1  
cffi                      1.12.3           py37h2e261b9_0  
chardet                   3.0.4                 py37_1003  
conda                     4.7.12                   py37_0  
conda-package-handling    1.5.0            py37h7b6447c_0  
cryptography              2.7              py37h1ba5d50_0  
future                    0.17.1                   pypi_0    pypi
h5py                      2.10.0                   pypi_0    pypi
idna                      2.8                      py37_0  
jmespath                  0.9.4                    pypi_0    pypi
joblib                    0.13.2                   pypi_0    pypi
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
ncurses                   6.1                  he6710b0_1  
niet                      1.5.1                    pypi_0    pypi
numpy                     1.17.2                   pypi_0    pypi
openssl                   1.1.1d               h7b6447c_1  
pip                       19.2.3                   pypi_0    pypi
pycosat                   0.6.3            py37h14c3975_0  
pycparser                 2.19                     py37_0  
pyopenssl                 19.0.0                   py37_0  
pysocks                   1.7.0                    py37_0  
python                    3.7.4                h265db76_1  
pyyaml                    5.1                      pypi_0    pypi
readline                  7.0                  h7b6447c_5  
requests                  2.22.0                   py37_0  
ruamel_yaml               0.15.46          py37h14c3975_0  
scikit-learn              0.21.3                   pypi_0    pypi
scipy                     1.3.1                    pypi_0    pypi
scrappie                  1.4.2                    pypi_0    pypi
setuptools                41.0.1                   py37_0  
six                       1.12.0                   py37_0  
sklearn                   0.0                      pypi_0    pypi
sqlite                    3.29.0               h7b6447c_0  
tk                        8.6.8                hbc83047_0  
tqdm                      4.32.1                     py_0  
urllib3                   1.24.2                   py37_0  
wheel                     0.33.4                   py37_0  
xz                        5.2.4                h14c3975_4  
yaml                      0.1.7                had09818_2  
zlib                      1.2.11               h7b6447c_3  
```

I tried installing your kit in a fresh conda 3.6 env and got similar issues, always a large list of incompatibililties and no info on what to do to correct.

Do you have more conda/python skills than me?
I hate snakes .....

**Comment by splaisan** [comment]
seems to have installed, finally.
Apparently python 7 does not like mlpy and python 3.6 on ly can install with pip and not with conda (sad as I do not like to pip too much.

Now I have a folder of numbered fast5 folders I would like to search for a primer, could you please help me run the right commands, your tutorial speaks about a signals.tsv but it is not clear to me what this is.
I have the kmer model ready as well as the name.index.gz but do not get the remaining of the requirements and commands from your tutorial.

What does SquigglePull.py do (_a dry run does not give me much info, is this normal?_)

```
/opt/biotools/miniconda3/envs/base3.6/bin/python /opt/biotools/SquiggleKit/SquigglePull.py -h
  File "/opt/biotools/SquiggleKit/SquigglePull.py", line 139
    print '{}\t{}\t{}\t{}\t{}'.format(
                             ^
SyntaxError: invalid syntax
```

**Comment by Psy-Fer** [comment]
Ahh, yes. I've not tested any of my tools with conda. Mostly because of my rather intense dislike of conda as a reliable bioinformatics framework, over just building clean and separate python environments.
