### ISSUE TITLE
MotifSeq read error

### ISSUE THREAD

**Issue by obehrto** [Psy-Fer/SquiggleKit#26]
Hi,

if I try to run MotifSeq on a folder of .fast5 files I get the following error:

Traceback (most recent call last):
  File "MotifSeq.py", line 339, in process_fast5
    c = list(hdf['Raw/Reads'].keys())
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/ole/.local/lib/python2.7/site-packages/h5py/_hl/group.py", line 264, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: 'Unable to open object (component not found)'
process_fast5():failed to extract events or fastq from: /media/sf_ONT/fast5_pass/FAL13819_42bda39cad99b93a371765a98b14b09ee42f3f16_0.fast5
main():data not extracted. Moving to next file - /media/sf_ONT/fast5_pass/FAL13819_42bda39cad99b93a371765a98b14b09ee42f3f16_0.fast5

This message is repeated for each file in the directory. Running MotifSeq with the provided example files works perfectly. Is this due to my files being multifast5 files?

Best,

Ole

**Comment by Psy-Fer** [comment]
Hello,

Ahh, yes. I need to push the latest update with multi fast5 support for that. 

I'm at a conference the next 2 days, I'll try and find the time to get it updated. 

James

**Comment by obehrto** [comment]
James,

thank you so much. Looking forward to the update. Keep up the great work!

Best, 

Ole

**Comment by Psy-Fer** [comment]
Mutli-fast5 support will be released in the next few weeks, however if you use SquigglePull on the multi-fast5 file with the multi-fast5 command on `--multi` , then use MotifSeq on the squiggle file, that should work.
