### ISSUE TITLE
Issue visualizing squiggles with recent fast5 file

### ISSUE THREAD

**Issue by mriekje** [Psy-Fer/SquiggleKit#42]
Hi, 

I'm trying to visualize some squiggles from a recent fast5 file using SquigglePlot and the following command:
` python3 SquigglePlot.py -m -i /Users/marieke/data/test/FAO01221_pass_d7290dd7_3.fast5
`

However, when I try this it gives me the following error:
```
Traceback (most recent call last):
  File "/Users/marieke/SquiggleKit/SquigglePlot.py", line 365, in <module>
    main()
  File "/Users/marieke/SquiggleKit/SquigglePlot.py", line 229, in main
    sig = sigs[args.readID]
KeyError: None
```

Trying to run SquigglePull on the same file gives me the same h5py error as #41.

The file was created with MinKNOW 20.10.6. I've tried using Python 2 and 3.

Any idea what's going on here and is there a fix for it?
Thanks, 
Marieke.

**Comment by Psy-Fer** [comment]
Hey, welcome to github.

So the error in squigglePlot seems to a missing argument, for the specific readID you want to plot in the fast5 file. 

Try copying the fast5 file into its own folder, then running the command with -m and -p /path/to/folder/

See if it works then? 

The rest I'll be investigating soon. Thanks for the issue 

Cheers, 
James

**Comment by hanost** [comment]
H, I am having this issue as well, but a different error message.

```
Traceback (most recent call last):
  File "/home/work/hwackel/Nanopore_project/SquiggleKit/SquigglePlot.py", line 433, in <module>
    main()
  File "/home/work/hwackel/Nanopore_project/SquiggleKit/SquigglePlot.py", line 275, in main
    view_sig(args, sig, read, fast5)
  File "/home/work/hwackel/Nanopore_project/SquiggleKit/SquigglePlot.py", line 421, in view_sig
    filename = os.path.join(args.save_path, "{}_dpi_{}_{}".format(name, args.dpi, args.save))
  File "/home/work/hwackel/.conda/envs/nanopore/lib/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by Psy-Fer** [comment]
Hello,

Could you please give me the command you are using?

At a quick glance this looks like --save was used without a valid file or --save_path path.

Cheers,
James
