### ISSUE TITLE
ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'headless' is currently running

### ISSUE THREAD

**Issue by vetmohit89** [Psy-Fer/SquiggleKit#62]
I am trying to run segmenter with the following command
 python segmenter.py -s data.tsv -ku -j 100 > signals_stall_segments.tsv

It is giving following error. 

Traceback (most recent call last):
  File "segmenter.py", line 4, in <module>
    import matplotlib.pyplot as plt
  File "/home/mbansal/.conda/envs/mlpy/lib/python3.6/site-packages/matplotlib/pyplot.py", line 2336, in <module>
    switch_backend(rcParams["backend"])
  File "/home/mbansal/.conda/envs/mlpy/lib/python3.6/site-packages/matplotlib/pyplot.py", line 287, in switch_backend
    newbackend, required_framework, current_framework))
ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'headless' is currently running

**Comment by Psy-Fer** [comment]
Hello,
This is probably because you don't have tkinter installed.

You can either try installing that, or try these 2 solutions.
1. comment out line 3 in segmenter.py 
`#matplotlib.use('TkAgg')`
2. change line 3 in segmenter.py to
`matplotlib.use('Agg')`

I hope this helps

James
